name: Build & Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - run: yarn install
        name: Install Deps

      - run: yarn run build
        name: Build Application

      - run: yarn test
        name: Run Tests
